{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2025-32914",
    "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
    "state": "PUBLISHED",
    "assignerShortName": "redhat",
    "dateReserved": "2025-04-14T01:59:13.828Z",
    "datePublished": "2025-04-14T14:45:46.300Z",
    "dateUpdated": "2025-04-14T15:05:37.281Z"
  },
  "containers": {
    "cna": {
      "title": "Libsoup: oob read on libsoup through function  \"soup_multipart_new_from_message\" in soup-multipart.c leads to crash or  exit of process",
      "metrics": [
        {
          "other": {
            "content": {
              "value": "Moderate",
              "namespace": "https://access.redhat.com/security/updates/classification/"
            },
            "type": "Red Hat severity rating"
          }
        },
        {
          "cvssV3_1": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 7.4,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
            "version": "3.1"
          },
          "format": "CVSS"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A flaw was found in libsoup, where the soup_multipart_new_from_message() function is vulnerable to an out-of-bounds read. This flaw allows a malicious HTTP client to induce the libsoup server to read out of bounds."
        }
      ],
      "affected": [
        {
          "vendor": "Red Hat",
          "product": "Red Hat Enterprise Linux 6",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "libsoup",
          "defaultStatus": "unknown",
          "cpes": [
            "cpe:/o:redhat:enterprise_linux:6"
          ]
        },
        {
          "vendor": "Red Hat",
          "product": "Red Hat Enterprise Linux 7",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "libsoup",
          "defaultStatus": "unknown",
          "cpes": [
            "cpe:/o:redhat:enterprise_linux:7"
          ]
        },
        {
          "vendor": "Red Hat",
          "product": "Red Hat Enterprise Linux 8",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "libsoup",
          "defaultStatus": "affected",
          "cpes": [
            "cpe:/o:redhat:enterprise_linux:8"
          ]
        },
        {
          "vendor": "Red Hat",
          "product": "Red Hat Enterprise Linux 9",
          "collectionURL": "https://access.redhat.com/downloads/content/package-browser/",
          "packageName": "libsoup",
          "defaultStatus": "affected",
          "cpes": [
            "cpe:/o:redhat:enterprise_linux:9"
          ]
        }
      ],
      "references": [
        {
          "url": "https://access.redhat.com/security/cve/CVE-2025-32914",
          "tags": [
            "vdb-entry",
            "x_refsource_REDHAT"
          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2359358",
          "name": "RHBZ#2359358",
          "tags": [
            "issue-tracking",
            "x_refsource_REDHAT"
          ]
        }
      ],
      "datePublic": "2025-04-14T00:00:00.000Z",
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-125",
              "description": "Out-of-bounds Read",
              "lang": "en",
              "type": "CWE"
            }
          ]
        }
      ],
      "x_redhatCweChain": "CWE-125: Out-of-bounds Read",
      "workarounds": [
        {
          "lang": "en",
          "value": "Currently, no mitigation is available for this vulnerability."
        }
      ],
      "timeline": [
        {
          "lang": "en",
          "time": "2025-04-14T01:21:01.384000+00:00",
          "value": "Reported to Red Hat."
        },
        {
          "lang": "en",
          "time": "2025-04-14T00:00:00+00:00",
          "value": "Made public."
        }
      ],
      "providerMetadata": {
        "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "shortName": "redhat",
        "dateUpdated": "2025-04-14T14:45:46.300Z"
      }
    },
    "adp": [
      {
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "timestamp": "2025-04-14T15:05:22.790979Z",
                "id": "CVE-2025-32914",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "role": "CISA Coordinator",
                "version": "2.0.3"
              }
            }
          }
        ],
        "title": "CISA ADP Vulnrichment",
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2025-04-14T15:05:37.281Z"
        }
      }
    ]
  }
}